### ISSUE TITLE
Nested 'multilist'

### ISSUE THREAD

**Issue by S1SYPHOS** [sylvainjule/kirby-multilist#11]
Hey there,
I don't know about prior Kirby versions, but editing nested 'multilist' entries isn't possible in v3.7. Thanks for your library!

Cheers,
S1SYPHOS

**Comment by sylvainjule** [comment]
Neither `structure` nor `multilist` fields are supported, see the list of [supported fields](https://github.com/sylvainjule/kirby-multilist?tab=readme-ov-file#3-supported-fields). I don't plan on adding these.
