### ISSUE TITLE
Keyboard shortcuts – movement and add a new row

### ISSUE THREAD

**Issue by adamkiss** [sylvainjule/kirby-multilist#3]
Hey Sylvain,

great field, thank you - and just at the moment I was interested in such field!

While working with it, I quickly grew frustrated with few things however - namely:

- I can't add a new row with keyboard only
- If I want to change a thing X rows up or down, I have to  <kbd>tab</kbd> or <kbd>shift-tab</kbd> however many times it's needed, even though the other cell is straight up or whatever

Would you be interested in accepting PR for keyboard shortcuts? I am not sure how hard it can be, but sometime next week I could try to add them. If you _would_ accept it, what would the shortcuts be? I find myself reaching for <kbd>⌘ + arrows</kbd> and <kbd>⌘ + enter</kbd> for new row, but would also accept any other option.

**Comment by sylvainjule** [comment]
Closed with 960efac ✓
