### ISSUE TITLE
Support for the hidden field

### ISSUE THREAD

**Issue by adamkiss** [sylvainjule/kirby-multilist#4]
The field works - it exists, can be changed, and is at least readonly, but it's still showing. Will you accept PR for hiding field of type `hidden`?

(or, can you add it please?)

**Comment by adamkiss** [comment]
Thank you @sylvainjule <3

**Comment by sylvainjule** [comment]
I did not lift a finger, @mrflix did all the work ;)

**Comment by adamkiss** [comment]
Oh, my bad. Thank you, @mrflix :)

**Comment by mrflix** [comment]
You're welcome! I needed it too :)
