### ISSUE TITLE
Kirby 3.6 support

### ISSUE THREAD

**Issue by mrflix** [sylvainjule/kirby-multilist#5]
Hey Sylvain! Thanks a lot for this great plugin. It's an essential to work fast with list content.
I just tried it for the first time with Kirby 3.6 and unfortunately it's UI is broken:

Kirby 3.5.x:

![Screenshot 2021-11-22 at 20 17 44](https://user-images.githubusercontent.com/60777/142921908-b6a485ae-c65d-4215-bc54-c0b515c9f719.png)

Kirby 3.6.0:

![Screenshot 2021-11-22 at 20 17 15](https://user-images.githubusercontent.com/60777/142921926-c92eee5a-f0ea-4203-91df-49ce0fd99e5d.png)

The table headers are very small, the drag-and-drop area is gone and the remove-button on the right is moved outside the field. I investigated and found the reason: the 38px height and width of all those elements was refactored into the variable `--item-height: 38px`. This variable is set on `.k-structure-field`.

I fixed it locally by adding it to `.k-multilist-table`:

```css
.k-multilist-table {
    --item-height: 38px;
}
```

**Comment by sylvainjule** [comment]
Thanks a lot for the PRs, I'm currently in the process of updating all my plugins for 3.6, so this is a tremendous help! I'll look into it soon!
